# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Ensures you get the latest stable version
          # Alternatively, specify a version:
          # flutter-version: '3.19.0' 

      - name: Install Dependencies
        run: flutter pub get # Use flutter pub, not dart pub for Flutter projects

      - name: Run Build Runner # Since you are using Riverpod/Supabase
        run: flutter pub run build_runner build --delete-conflicting-outputs
